language: generic
sudo: required
script:
  - echo $PATH 
  - swift test
  - swift run dns-sd --help
  - timeout --preserve-status -s INT --kill-after 10 5 swift run dns-sd -B _hap._tcp
  - timeout --preserve-status -s INT --kill-after 10 5 swift run dns-sd -E
  - timeout --preserve-status -s INT --kill-after 10 5 swift run dns-sd -F
  - timeout --preserve-status -s INT --kill-after 10 5 swift run dns-sd -L test _hap._tcp
  - timeout --preserve-status -s INT --kill-after 10 5 swift run dns-sd -R test _hap._tcp local 8000
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      install: PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    - os: osx
      osx_image: xcode10
      install: PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    - os: linux
      dist: trusty
      before_install:
        - sudo apt update
        - sudo apt install libavahi-compat-libdnssd-dev
        - wget https://swift.org/builds/swift-4.1.2-release/ubuntu1404/swift-4.1.2-RELEASE/swift-4.1.2-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.1.2-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-4.1.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
        - sudo hostname travis-ci.local
    - os: linux
      dist: trusty
      before_install:
        - sudo apt update
        - sudo apt install libavahi-compat-libdnssd-dev
        - wget https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.2-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-4.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
        - sudo hostname travis-ci.local
    - os: osx
      osx_image: xcode10
      before_install:
        - brew update
        - brew upgrade swiftlint
      script: swiftlint --strict
