language: generic
sudo: required
script: swift test
matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      dist: trusty
      install:
        - wget https://swift.org/builds/swift-4.1.2-release/ubuntu1404/swift-4.1.2-RELEASE/swift-4.1.2-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.1.2-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-4.1.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
